### ISSUE TITLE
Consider modernizing the repository

### ISSUE THREAD

**Issue by tychota** [hanaboso/amqplib-plus#3]
Hi, 

I was facing some issue when importing from "amqplib-plus/src/lib/whatever".

> Cannot use import outside of module

So i went in the process of modernizing the build scripts: you can look at it here https://github.com/tychota/amqplib-plus/tree/feat/modernize

or test here https://www.npmjs.com/package/@tychota/amqplib-plus

let me know what do you think.

**Comment by kedlas** [comment]
Hi, thanks for being interested in this package. Could you please create pull request containing your changes co we can see one single diff?

I see you replace mocha by jest. Any particular reason for this? The same for tsdx?

**Comment by tychota** [comment]
> Hi, thanks for being interested in this package. Could you please create pull request containing your changes co we can see one single diff?

Thank you for doing it. We may be using it on our project.
Sure

> The same for tsdx?

TSDX is the main changes of the PR, it is recommended by Typescript (even in the home page).

![image](https://user-images.githubusercontent.com/13785185/66330180-2a5dc080-e930-11e9-86ed-a9dbdfdcbd13.png)

With tsdx, you will end up having a single import that works for both js and ts

![image](https://user-images.githubusercontent.com/13785185/66330430-abb55300-e930-11e9-9e29-a3d1bdae721b.png)

![image](https://user-images.githubusercontent.com/13785185/66330490-ce476c00-e930-11e9-98ef-de9617fd4924.png)

> I see you replace mocha by jest. Any particular reason for this?

tsdx use jest by defaut. We can still use mocha, jasmine, chai, mockito but jest will be installed anyway.

Moreover Jest seems to take the lead on Mocha: see https://2018.stateofjs.com/testing/overview/

![image](https://user-images.githubusercontent.com/13785185/66330714-3a29d480-e931-11e9-811a-d763d9a70beb.png)

By removing the other deps, I did see that `mockito` wasn't use in practive, and neither was `jasmine` but were installed.

> I see you replace mocha by jest. Any particular reason for this? (2)

I also modernized tslint to eslint as former is deprecated.

**Comment by kedlas** [comment]
Hey Tycho, thanks for describing the changes. My fault that I didn't know tsdx. I haven't done anything in ts recently and haven't noticed it exists. What a shame. 

Anyway thanks for your PR, I will go through it today and if it does not break our dependant projects on this lib will merge it.

**Comment by kedlas** [comment]
Good job, @tychota. Thank you.

**Comment by kedlas** [comment]
Hi @tychota, I must reopen the issue. Integration tests in this lib are ok, consumer consumes the messages published by the publisher. However I started using this lib in my own project where only built files are used and when the message is consumed by the consumer, the `"Channel closed, Reason:"` event is fired.

I suspect the built code is not built properly. Do you use this lib in some of your project and do you face the same problem?

**Comment by kedlas** [comment]
Looks like this fix: https://github.com/hanaboso/amqplib-plus/commit/c5bc17144ebca8db7ee2bb4dd5cb0de53e2ecd9c saved the day.

Please use the latest `amqplib-plus@1.0.2` for testing.
