### ISSUE TITLE
Example in readme.md contains type errors

### ISSUE THREAD

**Issue by xamgore** [hanaboso/amqplib-plus#6]
Consumer is an abstract class according to ts definitions, but you call `new` on it. Why so?

**Comment by kedlas** [comment]
Hi, it is definitely a typo. There should be called new on some CustomConsumer that extends the Consumer. I will fix it ASAP. Thank you.

**Comment by kedlas** [comment]
Readme.md updated, can you have a look and possibly close this issue?

**Comment by xamgore** [comment]
Fixed in 4489f190889cef53eeb895f6c5f00202ec4794a1, thanks :)
