### ISSUE TITLE
How to connect via TLS ?

### ISSUE THREAD

**Issue by fbaldo31** [hanaboso/amqplib-plus#7]
Everything is in the title ;)
An example would be appreciated.
Thanks

**Comment by kedlas** [comment]
Hi Fred, currently it is not supported.

The Connection class must be modified in order to accept the tls config object according to http://www.squaremobius.net/amqp.node/ssl.html , but unfortunately it does not support it right now.

**Comment by kedlas** [comment]
If you know how to do it. feel free to send a pull request with desired change.
